<a href="https://colab.research.google.com/github/bowons/KNU-AI-Practice/blob/main/3-assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 과제1 - 로컬 환경에서 인공지능 환경설정 및 실행

In [1]:
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
import numpy as np

# 데이터셋 읽고 훈련 집합과 테스트 집합으로 분할
digit=datasets.load_digits()
x_train, x_test, y_train, y_test=train_test_split(digit.data, digit.target, train_size=0.8)

#svm의 분류 모델 SVC를 학습
s=svm.SVC(gamma=0.001)
s.fit(x_train,y_train)

res=s.predict(x_test)

# 혼동 행렬 구하기
conf=np.zeros((10,10))
for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

# 정확률 측정 및 출력 작업
no_correct=0
for i in range(10):
  no_correct += conf[i][i]
accuracy = no_correct/len(res)
print("테스트 집합에 대한 정확률은", accuracy*100,"%입니다.")

[[34.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 38.  0.  0.  0.  0.  0.  0.  2.  0.]
 [ 0.  0. 41.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 34.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 35.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 40.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 36.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 31.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 43.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 26.]]
테스트 집합에 대한 정확률은 99.44444444444444 %입니다.
