<a href="https://colab.research.google.com/github/bowons/KNU-AI-Practice/blob/main/4_AI_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perceptron

In [ ]:
import numpy as np
x2 = np.array([1,0,1])
w = np.array([-0.5, 1.0, 1.0])
s=sum(x2*w)

np.float64(0.5)

In [ ]:
import numpy as np
x = np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
w = np.array([-0.5, 1.0, 1.0])
s = np.sum(x*w, axis=1)

s

array([-0.5,  0.5,  0.5,  1.5])

## OR 데이터 인식

In [2]:
from sklearn.linear_model import Perceptron

#훈련 집합 구축
x = [[0,0],[0,1],[1,0],[1,1]]
y = [-1,1,1,1]

#fit 함수로 Perceptron 학습
p = Perceptron()
p.fit(x,y)

print("학습된 퍼셉트론의 매개변수:", p.coef_,p.intercept_)
print("훈련집합에 대한 예측: ",p.predict(x))
print("정확률 측정: ",p.score(x,y)*100,"%")



학습된 퍼셉트론의 매개변수: [[2. 2.]] [-1.]
훈련집합에 대한 예측:  [-1  1  1  1]
정확률 측정:  100.0 %


In [4]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import numpy as np

#데이터 셋을 읽고 훈련 집합과 테스트 집합으로 분할
digit=datasets.load_digits()
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target,train_size=0.6)

# fit 함수로 Perceptron 학습
p=Perceptron(max_iter=100, eta0=0.001, verbose=0)
p.fit(x_train,y_train) # digit 데이터로 모델링

res=p.predict(x_test) #테스트 집합으로 예측

# 혼동 행렬
conf=np.zeros((10,10))
for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

# 정확률 계산
no_correct = 0
for i in range(10):
  no_correct += conf[i][i]
accuracy = no_correct/len(res)
print("테스트 집합에 대한 정확률은 ", accuracy*100, "%입니다.")

[[70.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. 64.  3.  2.  4.  2.  1.  0.  6.  3.]
 [ 0.  0. 67.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 68.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 63.  0.  0.  2.  0.  0.]
 [ 2.  0.  0.  4.  0. 69.  0.  0.  0.  2.]
 [ 0.  0.  0.  1.  1.  1. 73.  0.  1.  0.]
 [ 0.  0.  0.  3.  0.  0.  0. 66.  0.  0.]
 [ 0.  0.  1.  5.  1.  0.  0.  1. 63.  5.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0. 63.]]
테스트 집합에 대한 정확률은  92.62865090403338 %입니다.


정확도의 결과가 SVM 모델보다 열등함
- 퍼셉트론은 선형 분류기이기 때문이다.

## 다층 퍼셉트론 프로그래밍

In [3]:
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import numpy as np

# 데이터셋을 읽고 훈련 집합과 테스트 집합으로 분할
digit=datasets.load_digits()
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target,train_size=0.6)

#MLP 분류기 모델을 학습
mlp=MLPClassifier(hidden_layer_sizes=(100),learning_rate_init=0.001,batch_size=32,max_iter=300,solver='sgd',verbose=True)
mlp.fit(x_train,y_train)

res=mlp.predict(x_test) #테스트 집합으로 예측

#혼동 행렬
conf=np.zeros((10,10))
for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

#정확률 계산
no_correct = 0
for i in range(10):
  no_correct+=conf[i][i]
accuracy=no_correct/len(res)
print("테스트 집합에 대한 정확률은 ", accuracy*100, "%입니다.")

Iteration 1, loss = 1.88722261
Iteration 2, loss = 0.32168255
Iteration 3, loss = 0.22515980
Iteration 4, loss = 0.17077716
Iteration 5, loss = 0.13990340
Iteration 6, loss = 0.11496338
Iteration 7, loss = 0.10379415
Iteration 8, loss = 0.08701073
Iteration 9, loss = 0.07805352
Iteration 10, loss = 0.07134141
Iteration 11, loss = 0.06002547
Iteration 12, loss = 0.05460012
Iteration 13, loss = 0.05153631
Iteration 14, loss = 0.04490045
Iteration 15, loss = 0.04355680
Iteration 16, loss = 0.04065333
Iteration 17, loss = 0.03658824
Iteration 18, loss = 0.03514514
Iteration 19, loss = 0.03232551
Iteration 20, loss = 0.03218663
Iteration 21, loss = 0.03080589
Iteration 22, loss = 0.02832055
Iteration 23, loss = 0.02616064
Iteration 24, loss = 0.02551886
Iteration 25, loss = 0.02360337
Iteration 26, loss = 0.02327202
Iteration 27, loss = 0.02282711
Iteration 28, loss = 0.02110618
Iteration 29, loss = 0.01999608
Iteration 30, loss = 0.01984492
Iteration 31, loss = 0.01859590
Iteration 32, los

실행결과
- 정확률이 SVM보다 약간 열등하고 퍼셉트론보다 우수한 것을 확인 가능

MNIST 데이터셋으로 필기 숫자 데이터셋을
다중 퍼셉트론으로 학습

In [4]:
from sklearn.datasets import fetch_openml
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt
import numpy as np

#MNIST 데이터셋을 읽고 훈련 집합과 테스트 집합으로 분할
mnist=fetch_openml('mnist_784')
mnist.data=mnist.data/255.0
x_train=mnist.data[:60000]; x_test=mnist.data[60000:]
y_train=np.int16(mnist.target[:60000]); y_test=np.int16(mnist.target[60000:])

#MLP 분류기 모델을 학습
mlp=MLPClassifier(hidden_layer_sizes=(100), learning_rate_init=0.001, batch_size=512, max_iter=300, solver='adam', verbose=True)
mlp.fit(x_train,y_train)

#테스트 집합으로 예측
res=mlp.predict(x_test)

#혼동 행렬
conf=np.zeros((10,10),dtype=np.int16)
for i in range(len(res)):
  conf[res[i]][y_test[i]]+=1
print(conf)

#정확률 계산
no_correct=0
for i in range(10):
  no_correct+=conf[i][i]
accuracy=no_correct/len(res)
print("테스트 집합에 대한 정확률은", accuracy*100, "%입니다.")

Iteration 1, loss = 0.60144503
Iteration 2, loss = 0.25678574
Iteration 3, loss = 0.20236959
Iteration 4, loss = 0.17001822
Iteration 5, loss = 0.14623603
Iteration 6, loss = 0.12839214
Iteration 7, loss = 0.11446056
Iteration 8, loss = 0.10269023
Iteration 9, loss = 0.09284866
Iteration 10, loss = 0.08497570
Iteration 11, loss = 0.07786103
Iteration 12, loss = 0.07105542
Iteration 13, loss = 0.06561940
Iteration 14, loss = 0.06047195
Iteration 15, loss = 0.05591091
Iteration 16, loss = 0.05147379
Iteration 17, loss = 0.04823711
Iteration 18, loss = 0.04450350
Iteration 19, loss = 0.04138081
Iteration 20, loss = 0.03860772
Iteration 21, loss = 0.03555504
Iteration 22, loss = 0.03331164
Iteration 23, loss = 0.03113687
Iteration 24, loss = 0.02892762
Iteration 25, loss = 0.02730144
Iteration 26, loss = 0.02514210
Iteration 27, loss = 0.02372297
Iteration 28, loss = 0.02196454
Iteration 29, loss = 0.01995595
Iteration 30, loss = 0.01888809
Iteration 31, loss = 0.01784605
Iteration 32, los

## 하이퍼 매개변수 최적화

In [ ]:
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection  import train_test_split, validation_curve
import numpy as np
import matplotlib.pyplot as plt
import time

# 데이터셋을 읽고 훈련 집합과 테스트 집합으로 분할
digit=datasets.load_digits()
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target,train_size=0.6)

#다층 퍼셉트론을 교차 검증으로 성능 평가 (소요시간 측정 포함)
start=time.time()
mlp=MLPClassifier(learning_rate_init=0.001, batch_size=32,max_iter=300, solver='sgd')
prange=range(50,1001,50)
train_score,test_score=validation_curve(mlp,x_train,y_train,param_name="hidden_layer_sizes",param_range=prange,cv=10,scoring="accuracy",n_jobs=4)
end=time.time()
print("하이퍼 매개변수 최적화에 걸린 시간은",end-start,"초입니다.")

#교차 검증 결과의 평균과 분산 구하기
train_mean = np.mean(train_score,axis=1)
train_std = np.std(train_score,axis=1)
test_mean = np.mean(test_score,axis=1)
test_std = np.std(test_score, axis=1)

#성능 그래프 그리기
plt.plot(prange,train_mean,label="Train score", color="r")
plt.plot(prange, test_mean, label="Test score", color="b")
plt.fill_between(prange, train_mean-train_std, train_mean+train_std, color="r", alpha=0.2)
plt.fill_between(prange, test_mean-test_std, test_mean+test_std, color="b", alpha=0.2)
plt.legend(loc="best")
plt.title("Validation Curve Mith MLP")
plt.xlabel("Number of hidden nodes"); plt.ylabel("Accuracy")
plt.ylim(0.9,1.01)
plt.grid(axis='both')
plt.show()

best_number_nodes=prange[np.argmax(test_mean)] # 최적의 은닉 노드 개수

print("\n최적의 은닉층의 노드 개수는", best_number_nodes, "개입니다.\n")

# 최적의 은닉 노드 개수로 모델링
mlp_test = MLPClassifier(hidden_layer_sizes=(best_number_nodes), learning_rate_init=0.001, batch_size=32, max_iter=300, solver='sgd')
mlp_test.fit(x_train, y_train)

# 테스트 집합으로 예측
res = mlp_test.predict(x_test)

# 혼동 행렬
conf = np.zeros((10, 10))
for i in range(len(res)):
    conf[res[i]][y_test[i]] += 1
print(conf)

# 정확률 계산
no_correct = 0
for i in range(10):
    no_correct += conf[i][i]
accuracy = no_correct / len(res)
print("테스트 집합에 대한 정확률은 ", accuracy * 100, "%입니다.")
